### ISSUE TITLE
remove 'textAnalyzer'

### ISSUE THREAD

**Issue by missinglink** [pelias/config#115]
This setting seems to have been removed in https://github.com/pelias/api/commit/0a95dd25838fc8cf12d7aecbf01603a477cf25d2 and no longer supported?

**Comment by Joxit** [comment]
It looks like yes, there is no occurrence of `textAnalyzer` in the API.

I do a PR to delete this from the default config ?

**Comment by orangejulius** [comment]
This should be safe to delete. We should also check if it's mentioned in the documentation anywhere.
