### ISSUE TITLE
Thoughts on using nconf

### ISSUE THREAD

**Issue by dianashk** [pelias/config#5]
Have we thought about using something like [nconf](https://github.com/flatiron/nconf) for this? I really like being able to override config options from the command line or ENV vars when testing and whatnot. This is obviously very low priority, but was just curious. It also allows you to merge various config files, as we are doing here already.

**Comment by dianashk** [comment]
I don't see a way to label this as a question. Maybe I don't have permissions for that. @missinglink @sevko @hkrishna

**Comment by sevko** [comment]
`nconf` looks very fully featured, and I'm all for using a mature package and not reinventing the wheel.

**Comment by dianashk** [comment]
I've used it in projects in the past and it generally does what you need. I would still like to keep it abstracted behind pelias-config and add our own logic in terms of which sources to merge config from, but yeah the wheel has been invented.

**Comment by hkrishna** [comment]
I've never used nconf but it looks good. I'm all for it :+1:
