### ISSUE TITLE
How to disable data sources?

### ISSUE THREAD

**Issue by arielmoraes** [pelias/config#58]
Is it possible to choose only one datasource? When I edit the pelias.json setting just the OSM importer it stills try to import data from the Who's on First.

**Comment by trescube** [comment]
@arielmoraes The OSM importer uses Who's on First to populate the administrative hierarchy but does not actually import Who's on First data as separate entities.  That is, if OSM contains an address for "30 West 26th St", the Pelias OSM importer looks up the neighbourhood, locality, region, and country from Who's on First based on the lat/lon of that OSM record.   The document in Elasticsearch would contain:

| type | value |
| ---- | ----- | 
| placetype | address | 
| number | 30 |
| street | West 26th St |
| neighbourhood | Flatiron District | 
| borough | Manhattan |
| locality | New York | 
| county | New York County |
| region | New York |
| country | United States | 

There would be no Who's on First records unless the Who's on First importer was enabled.

**Comment by trescube** [comment]
Here I'm starting an OSM import for Queens, NY and get the following output (truncated):  

```
[stephenhess@slumlord openstreetmap (master)]$ npm start

> pelias-openstreetmap@0.0.0-semantic-release start /Users/stephenhess/git/pelias/openstreetmap
> node index.js

2017-05-16T03:45:20.769Z - info: [openstreetmap] Creating read stream for: /Users/stephenhess/data/osm/queens_village_ny.osm.pbf
2017-05-16T03:45:21.877Z - info: [wof-pip-service:master] borough worker loaded 107 features in 0.57 seconds
2017-05-16T03:45:21.890Z - info: [wof-pip-service:master] dependency worker loaded 38 features in 0.582 seconds
2017-05-16T03:45:22.779Z - info: [wof-pip-service:master] macrocounty worker loaded 372 features in 1.442 seconds
2017-05-16T03:45:23.563Z - info: [wof-pip-service:master] macroregion worker loaded 83 features in 2.208 seconds
2017-05-16T03:45:38.212Z - info: [wof-pip-service:master] country worker loaded 218 features in 16.805 seconds
2017-05-16T03:45:39.076Z - info: [wof-pip-service:master] region worker loaded 4874 features in 17.658 seconds
2017-05-16T03:46:27.457Z - info: [wof-pip-service:master] neighbourhood worker loaded 64665 features in 66.036 seconds
2017-05-16T03:46:37.149Z - info: [wof-pip-service:master] county worker loaded 40211 features in 75.847 seconds
2017-05-16T03:46:44.589Z - info: [wof-pip-service:master] localadmin worker loaded 115187 features in 83.28 seconds
2017-05-16T03:47:11.820Z - info: [wof-pip-service:master] locality worker loaded 207866 features in 110.495 seconds
2017-05-16T03:47:11.821Z - info: [wof-pip-service:master] PIP Service Loading Completed!!!
2017-05-16T03:47:16.714Z - info: [openstreetmap-points] openstreetmap:venue:node:324334016 Hollis lon=-73.766668, lat=40.710172
2017-05-16T03:47:16.717Z - info: [openstreetmap-points] openstreetmap:venue:node:357544886 Andrew Jackson High School lon=-73.746594, lat=40.698072
2017-05-16T03:47:16.719Z - info: [openstreetmap-points] openstreetmap:venue:node:357548065 Belmont Park lon=-73.717909, lat=40.713991
[...]
```

All the `wof-pip-service:master` lines are from the point-in-polygon service starting up to lookup the administrative area data.  They aren't loading Who's on First.

**Comment by arielmoraes** [comment]
I see, but do I really need the files to be present? Because I'm getting the following errors:

```
2017-05-16T04:36:41.042Z - info: [openstreetmap] Creating read stream for: /Users/ariel/worldextracts/osm/brazil-latest.osm.pbf
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/ariel/worldextracts/whosonfirst/meta/wof-county-latest.csv'
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/ariel/worldextracts/whosonfirst/meta/wof-borough-latest.csv'
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/ariel/worldextracts/whosonfirst/meta/wof-localadmin-latest.csv'
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/ariel/worldextracts/whosonfirst/meta/wof-locality-latest.csv'
events.js:163
      throw er; // Unhandled 'error' event
      ^
```

and other some pbf2json error (truncated):

```
[pbf2json]: fatal error: unexpected signal during runtime execution
[pbf2json]: [signal 0xb code=0x1 addr=0x5a106fb594 pc=0x1274b]
[pbf2json]: 
[pbf2json]: runtime stack:
[pbf2json]: runtime.throw(0x2e66a0, 0x2a)
[pbf2json]: 	/usr/local/go/src/runtime/panic.go:547 +0x90
[pbf2json]: runtime.sigpanic()
[pbf2json]: 	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
[pbf2json]: runtime.unlock(0x3ecea0)
[pbf2json]: 	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
[pbf2json]: runtime.(*mheap).alloc_m(0x3ecea0, 0x238, 0x100000000, 0x4d9d08)
[pbf2json]: 	/usr/local/go/src/runtime/mheap.go:492 +0x314
[pbf2json]: runtime.(*mheap).alloc.func1()

```

**Comment by arielmoraes** [comment]
I see, I will download the files now, thank you.

**Comment by arielmoraes** [comment]
Now it started to import data from OSM but it gets stuck and the pbf2json process CPU usage increases :(. Am I missing something?

**Comment by missinglink** [comment]
Hi @arielmoraes could you please provide some information about what you would like to achieve and the names of the import files you are using + their sizes?

I wouldn't worry about CPU usage for pbf2json, that means it's working, it's also normal for you to see short bursts of CPU usage followed by a lull, this is due to the kernel putting the process to sleep (you can see the process state using a tool like `top`)

Regarding the `"-0300 kernel AMFI` error, I don't have a mac so I can't confirm, could you please copy-> paste a few logs and the command you used to generate them.

Lastly, could you please post the specs of the machine you are using, particularly CPU and RAM.

Thanks!

**Comment by arielmoraes** [comment]
@missinglink, I'm trying to host the Pelias environment. I'm using 3 sources: a Brazil pbf file, the admin data from Who's on First and the roads polyline. The first one is ~450 Mb in size, the other two have the same size that is explained in their repositories.

Yes indeed, the processor usage of pbf2json is a sign that everything is working normally, but in my case, when the process hangs, I can no longer see output in the Terminal. And this is random, sometimes a exception from pbf2json is thrown stating something about the file lock, sometimes it hangs after PIP Service Loading Completed!!! and sometimes it can go event further loading some nodes. There was only one time which all nodes were loaded, but it stopped when inserting the data into ES.

I couldn't find any logs besides this one. 

I'm using a machine with a core i7 5th generation and 16 GB of RAM.

**Comment by arielmoraes** [comment]
@missinglink here is a output, this time with an exception thrown by the pbf2json (truncated):

```
2017-05-16T15:56:14.045Z - info: [openstreetmap] Creating read stream for: /Users/ariel/worldextracts/osm/brazil-latest.osm.pbf
[pbf2json]: fatal error: unexpected signal during runtime execution
[pbf2json]: fatal error: unexpected signal during runtime execution
[pbf2json]: [signal 0xb code=0x1 addr=0x768b2116ca pc=0x1274b]
[pbf2json]: 
[pbf2json]: runtime stack:
[pbf2json]: runtime.throw(0x2e66a0, 0x2a)
[pbf2json]: 	/usr/local/go/src/runtime/panic.go:547 +0x90
[pbf2json]: runtime.sigpanic()
[pbf2json]: 	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
[pbf2json]: runtime.unlock(0x3ecea0)
[pbf2json]: 	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
[pbf2json]: runtime.(*mheap).freeSpan.func1()
[pbf2json]: 	/usr/local/go/src/runtime/mheap.go:726 +0x186
[pbf2json]: runtime.systemstack(0xc820191c48)
[pbf2json]: 	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
[...]
[pbf2json]: runtime.systemstack(0xc820026000)
[pbf2json]: 	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
[pbf2json]: runtime.mstart()
[pbf2json]: 	/usr/local/go/src/runtime/proc.go:1051
2017-05-16T15:56:14.938Z - info: [wof-pip-service:master] dependency worker loaded 38 features in 0.505 seconds
2017-05-16T15:56:14.989Z - info: [wof-pip-service:master] borough worker loaded 107 features in 0.57 seconds
2017-05-16T15:56:15.783Z - info: [wof-pip-service:master] macrocounty worker loaded 372 features in 1.284 seconds
2017-05-16T15:56:17.376Z - info: [wof-pip-service:master] macroregion worker loaded 83 features in 2.908 seconds
```

Note that the import process continues even if an exception is thrown.

**Comment by missinglink** [comment]
interesting, so you solved this by recompiling `pbf2json` on your mac using a newer version of `Go`?

**Comment by arielmoraes** [comment]
@missinglink , yes, but this was not related with the version of `Go`. The pbf2json dependency of the importer was not recompiled when I executed the npm install command and the package has a build folder with some binaries already built, so the importer was using an old version of the pbf2json.

**Comment by missinglink** [comment]
ok, thanks @arielmoraes I recompiled it on all architectures in https://github.com/pelias/pbf2json/pull/43, would it be possible for you to check that the binary I generated works on your system?

```
$ shasum build/*
b85bf415472db92c702dd81954ca8fde66f9cc98  build/pbf2json.darwin-x64
94cc8adf33d6a410a7c9e612c7280a04524e81ee  build/pbf2json.linux-arm
f7ac7b00ec2725ce0d5ec23c00347308a9b8c755  build/pbf2json.linux-x64
0ff83be23a6e5530fc0f558e104894adfaa72062  build/pbf2json.win32-x64
```

thanks for letting us know, once that PR is merged I will push those binaries to `npm`.

**Comment by missinglink** [comment]
I also noticed that the `file` command generated slightly different output than previously:

```
$ file build/pbf2json.darwin-x64
build/pbf2json.darwin-x64: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS>
```

it never used to say `flags:<NOUNDEFS>`, does your native OSX compilation produce the same result?
