### ISSUE TITLE
fail on npm install pelias-config

### ISSUE THREAD

**Issue by hupohs** [pelias/config#75]
I am totally lost at the beginning.  I am try to follow readme to create ~/pelias.json. I failed on the first step.this is my step
$ git clone https://github.com/pelias/config.git
$ cd config
$ npm install pelias-config
then i get npm error as following:
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "pelias-config" under a package
npm ERR! also called "pelias-config". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hupo/.npm/_logs/2018-01-18T06_55_54_793Z-debug.log

anyone can tell me what to do?

**Comment by orangejulius** [comment]
Hey @hupohs,
You should not have to install this repository directly to do anything with pelias. Take a look at our [how to guide](https://github.com/pelias/dockerfiles/blob/master/how_to_guide.pdf) for the most up to date installation instructions. Let me know if you have any questions.

**Comment by orangejulius** [comment]
I think we answered this question, if there's anything else please let us know.
